name: run-tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest, windows-latest]
                php: [8.0, 7.4, 7.3, 7.2]
                dependency-version: [prefer-lowest, prefer-stable]

        name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    extensions: pcov
                    coverage: none

            -   name: Install dependencies
                run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            -   name: Setup PCOV
                run: |
                  composer require pcov/clobber
                  vendor/bin/pcov clobber

            -   name: Execute tests
                run: vendor/bin/phpunit
